---
- hosts: all
  become: yes
  become_user: deploy
  vars:
    prysm_user: deploy
    validator_wallet_name: v
    validator_accounts_password: foobar
    prysm_install_path: /opt/prysm-docker-compose
    
  roles:
  - keystore-wallet