---
- hosts: all
  become: yes
  become_user: {{ prysm_user }}
  vars_files:
  - ./vars/vars.yaml
  - ./vars/validator-accounts-to-import.yaml
  
  roles:
  - create-validator-wallet
  - import-validator-accounts