---
- name: Create wallet
  command: /home/{{ prysm_user }}/go/bin/ethdo wallet create --wallet="{{ withdrawal_wallet_name }}" --type="{{ withdrawal_wallet_type }}" --walletpassphrase="{{ withdrawal_wallet_password }}"

- name: Read wallet seed
  command: /home/{{ prysm_user }}/go/bin/ethdo wallet seed --wallet="{{ withdrawal_wallet_name }}" --walletpassphrase="{{ withdrawal_wallet_password }}"
  register: wallet_seed
  when: withdrawal_wallet_type == "hd"
  
- name: Your wallet seed (write it down and store it safe!)
  debug:
    msg: "{{ wallet_seed }}"

- name: Create account
  command: /home/{{ prysm_user }}/go/bin/ethdo account create --account="{{ withdrawal_wallet_name }}/{{ withdrawal_account_name }}" --walletpassphrase="{{ withdrawal_wallet_password }}"  --passphrase="{{ withdrawal_account_password }}"