---
- name: Install required system packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
  - git
  - vim

- name: Clone Ethereum 2.0 docker compose setup
  git:
    repo: "https://github.com/stefa2k/prysm-docker-compose"
    dest: /opt/prysm-docker-compose

- name: Change file ownership and group of clone
  file:
    state: directory
    path: /opt/prysm-docker-compose
    owner: deploy
    group: deploy
    recursive: yes

- name: Configure correct IP address for node
  lineinfile:
    path: /opt/prysm-docker-compose/config/beacon.yaml
    regexp: '^p2p-host-ip: '
    line: 'p2p-host-ip: {{ ansible_enp0s31f6.ipv4.address }}'



