---
- name: Install required system packages
  apt: 
    name: "{{ item }}" 
    state: latest 
    update_cache: yes
  loop: 
  - git

- name: ufw allow filebeat from specific ips
  ufw:
    rule: allow
    port: 5044
    src: "{{ item }}"
  with_items: "{{ filebeat_src }}"
    
- name: ufw deny filebeat from all other ips
  ufw:
    rule: deny
    port: 5044

- name: ufw allow kibana from specific ips
  ufw:
    rule: allow
    port: 5601
    src: "{{ item }}"
  with_items: "{{ kibana_src }}"

- name: ufw deny kibana from all other ips
  ufw:
    rule: deny
    port: 5601

- name: Clone docker-elk
  git:
    repo: "https://github.com/stefa2k/docker-elk"
    dest: "{{ elk_install_path }}"

- name: Change file ownership and group of clone
  file:
    state: directory
    path: "{{ elk_install_path }}"
    owner: "{{ elk_user }}"
    group: "{{ elk_user }}"
    recurse: yes

- name: Configure logstash filter
  blockinfile:
    path: "{{ elk_install_path }}/config/logstash/pipeline/logstash.conf"
    backup: yes
    insertafter: "## Add your filters / logstash plugins configuration here"
    block: |
      filter {
        kv {
          source => "message"
        }
      }

- name: Start ELK
  command: docker-compose up -d
  args:
    chdir: "{{ elk_install_path }}"